linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - depguard
    - dupl
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - misspell
    - nakedret
    - prealloc
    - exportloopref
    - stylecheck
    - unconvert
    - unparam
    - revive
    - gochecknoglobals

run:
  skip-dirs:
    - vendor
